In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import random

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([1,8,12,16,20,24,28,32,36,40])
x = np.reshape(x,(10,1))
y = np.reshape(y,(10,1))

In [3]:
beta = np.array([[1],[0]])

In [4]:
def Pred_Val(x,y,beta):
    df_x = np.column_stack(((np.ones((len(x),1),dtype=int)),x))
    out_df = df_x.dot(beta)
    return df_x,out_df

In [5]:
def cost_fun(y,y_pred):
    mse = sum((y-y_pred)**2)/len(y)
    return mse

In [6]:
x_new,y_new = Pred_Val(x,y,beta)

In [7]:
Mean_Sqr_Err = cost_fun(y,y_new)

In [8]:
Mean_Sqr_Err

array([572.1])

In [9]:
def delta_val(in_df,out_df,out_df_new):
    delta = (in_df.transpose().dot(out_df-out_df_new))/len(in_df)
    return delta

In [10]:
delta_val(x_new,y,y_new)

array([[ 20.7],
       [148.2]])

In [15]:
def fun_train(in_df,out_df,ler_rate,itr,conv):
    b0 = -1
    b1 = 2
    beta = np.array([[b0],[b1]])
    perr = 0
    for i in range(1,itr+1):
        #beta = np.array([[b0],[b1]])
        x1,y1 = Pred_Val(in_df,out_df,beta)
        cerr = cost_fun(out_df,y1)
        diff = abs(perr-cerr)
        if i%50 ==0:
            print('cerr {} at iteration {}'.format(cerr,i))
        j = 0
        if (diff <= conv):
            print('Training Done at {} iteration and mse is {},perr is {} and diff is {}'.format(i,cerr,perr,diff))
            j = 1
            break
        delta = delta_val(x1,out_df,y1)
        beta = beta + (ler_rate*delta)
        perr = cerr
    if (j==0):
        print('Training is not yet done and iterations are completed and Mean Square Error is: {}'.format(cerr))
    return beta

In [17]:
coef = fun_train(x,y,0.01,100000,0.0001)

cerr [0.63277448] at iteration 50
cerr [0.62449312] at iteration 100
cerr [0.61778171] at iteration 150
Training Done at 196 iteration and mse is [0.61273692],perr is [0.61283654] and diff is [9.96160204e-05]


In [26]:
coef

array([[-0.86783151],
       [ 4.1159235 ]])

In [18]:
y_new_f = x_new.dot(coef)

In [25]:
pd.DataFrame(data = {'y_init':np.reshape(y,(10,)), 'y_pred_inint':np.reshape(y_new,(10,)), 'y_pred_f':np.reshape(y_new_f,(10,))})

y_init  y_pred_inint   y_pred_f
0       1             1   3.248092
1       8             1   7.364015
2      12             1  11.479939
3      16             1  15.595862
4      20             1  19.711786
5      24             1  23.827709
6      28             1  27.943633
7      32             1  32.059556
8      36             1  36.175480
9      40             1  40.291403