In [1]:
pwd

'C:\\Users\\1239658'

In [2]:
# Python built-in function range generates a list iterator
x = range(1,10)
print(list(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
#importing Numpy package/Module
import numpy as np

In [4]:
# In Pythom 3.X the 'arange' function generates array-- arange is Numpy function
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


###### Python built-in function range
'''class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement)'''

In [5]:
# Numpy linspace function
print(np.linspace(1,10)) # Default value is 50 samples

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [6]:
print(np.linspace(1,10,5)) # num = 5 'endpoint' default value is TRUE

[ 1.    3.25  5.5   7.75 10.  ]


In [7]:
print(np.linspace(1,10,3,endpoint=False)) # here explicitly we define endpoint = False (10-Excluded)

[1. 4. 7.]


In [8]:
#If the optional parameter 'retstep' is set, the function will also return the value of the spacing between adjacent values. 
#So, the function will return a tuple ('samples', 'step')

print(np.linspace(1,10,5,retstep=True))

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


In [9]:
# Zero Dimensional Array
x = np.array(10)
print("x: ",x)
print("The type of x: ",type(x))
print("The dimension of x: ",np.ndim(x))

x:  10
The type of x:  <class 'numpy.ndarray'>
The dimension of x:  0


In [10]:
# one dimensional Array
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])
print("F: ", F)
print("V: ", V)
print("Type of F: ", F.dtype)
print("Type of V: ", V.dtype)
print("Dimension of F: ", np.ndim(F))
print("Dimension of V: ", np.ndim(V))

F:  [ 1  1  2  3  5  8 13 21]
V:  [ 3.4  6.9 99.8 12.8]
Type of F:  int32
Type of V:  float64
Dimension of F:  1
Dimension of V:  1


In [14]:
# 2 Dimensional & Multi Dimensional
x = np.array([[1,2,3],[4,5,6]])
print(x)
print('The Dimension of X: ',np.ndim(x))

[[1 2 3]
 [4 5 6]]
The Dimension of X:  2


In [15]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
print('y = ',y)
print('The Dimension of y : ',np.ndim(y))

y =  [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]
The Dimension of y :  2


In [28]:
z = np.array([[[1,2,3],[4,5,6]],
              [[1,3,5],[6,8,0]] ])
print('z =',z)
print('The Dimension of z : ',np.ndim(z))

z = [[[1 2 3]
  [4 5 6]]

 [[1 3 5]
  [6 8 0]]]
The Dimension of z :  3


#### Shape function
The "shape" of an array is a tuple with the number of elements per axis (dimension). In our example, the shape is equal to (6, 3), i.e. we have 6 lines and 3 columns

In [30]:
x1 = np.array([ [67, 63, 87],
               [77, 69, 59],
               [85, 87, 99],
               [79, 72, 71],
               [63, 89, 93],
               [68, 92, 78]])
print(np.shape(x1))

(6, 3)


In [36]:
# "shape" can also be used to change the shape of an array.

x1.shape = (2,9)
print(x1)

[[67 63 87 77 69 59 85 87 99]
 [79 72 71 63 89 93 68 92 78]]


In [38]:
x1.shape = (3,6)
print(x1)

[[67 63 87 77 69 59]
 [85 87 99 79 72 71]
 [63 89 93 68 92 78]]
